version: "3.8"
services:
  analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_NAME: postgres
      DB_PASS: SuperSekretPassword
  db:
    image: "postgres:15.2"
    restart: always
    environment:
      POSTGRES_PASSWORD: SuperSekretPassword
    ports:
      - "5432:5432"
