version: "3.8"
services:
  analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - nielsdb
    volumes:
      - type: bind
        source: $SOURCE_M2 # set this in '.env' in the same directory as docker-compose.yml
        target: /root/.m2
  nielsdb:
    image: "postgres:15.2"
    restart: always
    environment:
      POSTGRES_PASSWORD: SuperSekretPassword
    ports:
      - "5469:5432"