extractors:
  - nl.tudelft.mavensecrets.extractors.CompilerConfigExtractor
  - nl.tudelft.mavensecrets.extractors.JavaModuleExtractor
  - nl.tudelft.mavensecrets.extractors.JavaVersionExtractor
  - nl.tudelft.mavensecrets.extractors.ParentExtractor
  - nl.tudelft.ExtractorVC
  - nl.tudelft.DemoExtractor 