extractors:
  - nl.tudelft.mavensecrets.extractors.ArtifactExistsExtractor
  - nl.tudelft.mavensecrets.extractors.CompilerConfigExtractor
#  - nl.tudelft.mavensecrets.extractors.DependencyExtractor
  - nl.tudelft.mavensecrets.extractors.EmbedExtractor
  - nl.tudelft.mavensecrets.extractors.ExtractorVC
  - nl.tudelft.mavensecrets.extractors.JavaModuleExtractor
  - nl.tudelft.mavensecrets.extractors.JavaVersionExtractor
  - nl.tudelft.mavensecrets.extractors.LanguageExtractor
  - nl.tudelft.mavensecrets.extractors.MismatchedPackagesExtractor
  - nl.tudelft.mavensecrets.extractors.PackagingTypeExtractor
  - nl.tudelft.mavensecrets.extractors.ParentExtractor
#  - nl.tudelft.mavensecrets.extractors.SizeExtractor

threads: 12

database:
  hostname: localhost
  port: 5432
  name: postgres
  username: postgres
  password: SuperSekretPassword

indexfile: ~

m2-dir: ~

seed: 69420

sample-percentage: 0.1
